server:
  port : 9095
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/moneytransfer
    username: moneytransferuser
    password: '!QAZxsw2'
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # create table if it doesn't exist. If it exists and if there is any change, update.
    # Optional
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect

